#!/usr/bin/env bash
# setup.sh — detect GPU, recommend model/backend, write .env
set -euo pipefail

CYAN='\033[96m'
GREEN='\033[92m'
YELLOW='\033[93m'
DIM='\033[2m'
RESET='\033[0m'

echo ""
echo -e "${CYAN}claude-autonaumous setup${RESET}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# ── Detect GPU VRAM ───────────────────────────────────────────────────────────

VRAM_MB=0
GPU_NAME="unknown"

if command -v nvidia-smi &>/dev/null; then
    VRAM_MB=$(nvidia-smi --query-gpu=memory.total --format=csv,noheader,nounits 2>/dev/null | head -1 | tr -d ' ' || echo 0)
    GPU_NAME=$(nvidia-smi --query-gpu=name --format=csv,noheader 2>/dev/null | head -1 | xargs || echo "unknown")
    echo -e "GPU:  ${GREEN}${GPU_NAME}${RESET} (${VRAM_MB} MB VRAM)"
else
    echo -e "${YELLOW}nvidia-smi not found — can't detect GPU${RESET}"
    echo "Set LOCAL_MODEL_URL and LOCAL_MODEL_NAME manually in .env"
fi

# ── Recommend model and backend ───────────────────────────────────────────────

OLLAMA_MODEL=""
VLLM_MODEL=""
RECOMMENDED_BACKEND=""
VLLM_EXTRA_ARGS="--trust-remote-code --enforce-eager --enable-auto-tool-choice --tool-call-parser hermes"

if   [ "$VRAM_MB" -ge 75000 ]; then
    OLLAMA_MODEL="qwen2.5-coder:32b"
    VLLM_MODEL="Qwen/Qwen3-235B-A22B"
    VLLM_EXTRA_ARGS="--trust-remote-code --enforce-eager --enable-auto-tool-choice --tool-call-parser qwen3_xml"
    RECOMMENDED_BACKEND="vllm"
    TIER="80 GB+"
elif [ "$VRAM_MB" -ge 40000 ]; then
    OLLAMA_MODEL="qwen2.5-coder:32b"
    VLLM_MODEL="Qwen/Qwen2.5-72B-Instruct"
    RECOMMENDED_BACKEND="vllm"
    TIER="48 GB"
elif [ "$VRAM_MB" -ge 20000 ]; then
    OLLAMA_MODEL="qwen2.5-coder:32b-instruct-q4_K_M"
    VLLM_MODEL="Qwen/Qwen2.5-32B-Instruct"
    RECOMMENDED_BACKEND="ollama"
    TIER="24 GB"
elif [ "$VRAM_MB" -ge 12000 ]; then
    OLLAMA_MODEL="qwen2.5-coder:14b"
    VLLM_MODEL="Qwen/Qwen2.5-14B-Instruct"
    RECOMMENDED_BACKEND="ollama"
    TIER="16 GB"
elif [ "$VRAM_MB" -ge 6000 ]; then
    OLLAMA_MODEL="qwen2.5-coder:7b"
    VLLM_MODEL="Qwen/Qwen2.5-7B-Instruct"
    RECOMMENDED_BACKEND="ollama"
    TIER="8 GB"
else
    OLLAMA_MODEL="qwen2.5-coder:7b"
    VLLM_MODEL="Qwen/Qwen2.5-7B-Instruct"
    RECOMMENDED_BACKEND="ollama"
    TIER="unknown"
fi

echo -e "Tier: ${GREEN}${TIER}${RESET}"
echo ""

# ── Ask which backend ─────────────────────────────────────────────────────────

echo "Recommended backend: ${RECOMMENDED_BACKEND}"
echo ""
echo "  1) Ollama  (easiest — install from https://ollama.com)"
echo "  2) vLLM    (Docker — better throughput, 24 GB+ recommended)"
echo "  3) Other   (any OpenAI-compatible server — configure manually)"
echo ""
read -rp "Choose backend [1/2/3, default: 1]: " BACKEND_CHOICE
BACKEND_CHOICE="${BACKEND_CHOICE:-1}"

case "$BACKEND_CHOICE" in
    2)
        BACKEND="vllm"
        MODEL_NAME="${VLLM_MODEL}"
        MODEL_URL="http://127.0.0.1:8000/v1/chat/completions"
        ;;
    3)
        BACKEND="other"
        read -rp "Model endpoint URL [http://127.0.0.1:8000/v1/chat/completions]: " MODEL_URL
        MODEL_URL="${MODEL_URL:-http://127.0.0.1:8000/v1/chat/completions}"
        read -rp "Model name (as expected by the server): " MODEL_NAME
        ;;
    *)
        BACKEND="ollama"
        MODEL_NAME="${OLLAMA_MODEL}"
        MODEL_URL="http://127.0.0.1:11434/v1/chat/completions"
        ;;
esac

echo ""
echo -e "${DIM}Model:    ${MODEL_NAME}${RESET}"
echo -e "${DIM}Endpoint: ${MODEL_URL}${RESET}"
echo ""

# ── Write .env ────────────────────────────────────────────────────────────────

ENV_FILE="$(dirname "$0")/.env"

cat > "$ENV_FILE" <<EOF
# Generated by setup.sh — $(date)
# GPU: ${GPU_NAME} (${VRAM_MB} MB)

LOCAL_MODEL_URL=${MODEL_URL}
LOCAL_MODEL_NAME=${MODEL_NAME}
LOCAL_MODEL_TIMEOUT=120
STREAM_OUTPUT=true

# VLLM_MODEL=${VLLM_MODEL}
# VLLM_EXTRA_ARGS=${VLLM_EXTRA_ARGS}

# Optional
# WORKSPACE_DIR=~/my-project
# CLAUDE_MODEL=claude-sonnet-4-6
# ENABLE_REVIEWER=false
# MAX_RETRIES=3
# ROUTER_MODE=heuristic
EOF

echo -e "${GREEN}✓ .env written${RESET}"

# ── Next steps ────────────────────────────────────────────────────────────────

echo ""
echo "Next steps:"
echo ""

if [ "$BACKEND" = "ollama" ]; then
    echo "  1. Install Ollama: https://ollama.com/download"
    echo "  2. Pull the model:"
    echo "       ollama pull ${MODEL_NAME}"
    echo "  3. Start the server:"
    echo "       bash server/ollama.sh"
elif [ "$BACKEND" = "vllm" ]; then
    echo "  1. Edit .env — set VLLM_MODEL and adjust VLLM_EXTRA_ARGS if needed"
    echo "  2. Start vLLM:"
    echo "       docker compose up -d"
else
    echo "  1. Start your model server"
fi

echo ""
echo "  Check server:   curl http://127.0.0.1:8000/health"
echo "  Add alias:      echo \"alias qwen='python3 \$HOME/claude-autonaumous/qwen_cli.py'\" >> ~/.bashrc"
echo "  Register MCP:   claude mcp add qwen-hybrid -- python3 ~/claude-autonaumous/mcp_server.py"
echo "  Run pipeline:   python3 ~/claude-autonaumous/main.py"
echo ""
